import { WebsiteContent } from './types'

export const DEFAULT_WEBSITE_CONTENT: Partial<WebsiteContent>[] = [
  // Homepage Hero
  {
    content_key: 'home.hero.subtitle',
    content_value: 'Since 1964',
    content_type: 'text',
    group_name: 'homepage',
    label: 'Hero Subtitle',
    description: 'The small text above the main hero title',
  },
  {
    content_key: 'home.hero.title',
    content_value: 'Building Workspaces That Perform',
    content_type: 'text',
    group_name: 'homepage',
    label: 'Hero Title',
    description: 'The main hero section title',
  },
  {
    content_key: 'home.hero.description',
    content_value: 'Precision engineering meets architectural elegance. We deliver premium turnkey solutions for the modern corporate environment.',
    content_type: 'text',
    group_name: 'homepage',
    label: 'Hero Description',
    description: 'The hero section description text',
  },
  {
    content_key: 'home.hero.cta_text',
    content_value: 'Explore Office Sets',
    content_type: 'text',
    group_name: 'homepage',
    label: 'Hero CTA Text',
    description: 'The text for the hero call-to-action button',
  },
  {
    content_key: 'home.hero.cta_link',
    content_value: '/products/office-sets',
    content_type: 'text',
    group_name: 'homepage',
    label: 'Hero CTA Link',
    description: 'The URL for the hero call-to-action button',
  },
  {
    content_key: 'home.hero.background_image',
    content_value: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=2000&q=80',
    content_type: 'image',
    group_name: 'homepage',
    label: 'Hero Background Image',
    description: 'The background image for the hero section',
  },

  // Homepage Stats
  {
    content_key: 'home.stats.stat1.value',
    content_value: '60+',
    content_type: 'text',
    group_name: 'homepage',
    label: 'Stat 1 Value',
    description: 'The value for the first statistic',
  },
  {
    content_key: 'home.stats.stat1.label',
    content_value: 'Years of Heritage',
    content_type: 'text',
    group_name: 'homepage',
    label: 'Stat 1 Label',
    description: 'The label for the first statistic',
  },
  {
    content_key: 'home.stats.stat2.value',
    content_value: '300+',
    content_type: 'text',
    group_name: 'homepage',
    label: 'Stat 2 Value',
    description: 'The value for the second statistic',
  },
  {
    content_key: 'home.stats.stat2.label',
    content_value: 'Corporate Clients',
    content_type: 'text',
    group_name: 'homepage',
    label: 'Stat 2 Label',
    description: 'The label for the second statistic',
  },
  {
    content_key: 'home.stats.stat3.value',
    content_value: '500+',
    content_type: 'text',
    group_name: 'homepage',
    label: 'Stat 3 Value',
    description: 'The value for the third statistic',
  },
  {
    content_key: 'home.stats.stat3.label',
    content_value: 'Workspaces Delivered',
    content_type: 'text',
    group_name: 'homepage',
    label: 'Stat 3 Label',
    description: 'The label for the third statistic',
  },

  // Homepage Legacy Section
  {
    content_key: 'home.legacy.title',
    content_value: 'A Legacy of Craftsmanship',
    content_type: 'text',
    group_name: 'homepage',
    label: 'Legacy Section Title',
    description: 'The title for the legacy/craftsmanship section',
  },
  {
    content_key: 'home.legacy.description1',
    content_value: 'Founded by Mr. Tahir Hassan Gardezi, HB Furniture has stood as a paragon of industrial excellence since 1964. What began as a visionary pursuit of quality has evolved into a comprehensive institution for workspace creation.',
    content_type: 'text',
    group_name: 'homepage',
    label: 'Legacy Description 1',
    description: 'First paragraph of the legacy section',
  },
  {
    content_key: 'home.legacy.description2',
    content_value: 'Our approach blends heritage manufacturing principles with cutting-edge architectural design. We don\'t just supply furniture; we engineer environments that foster productivity, well-being, and corporate prestige.',
    content_type: 'text',
    group_name: 'homepage',
    label: 'Legacy Description 2',
    description: 'Second paragraph of the legacy section',
  },
  {
    content_key: 'home.legacy.image',
    content_value: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1000&q=80',
    content_type: 'image',
    group_name: 'homepage',
    label: 'Legacy Section Image',
    description: 'The image for the legacy section',
  },

  // Homepage Clients Section
  {
    content_key: 'home.clients.subtitle',
    content_value: 'Our Prestige Clients',
    content_type: 'text',
    group_name: 'homepage',
    label: 'Clients Section Subtitle',
    description: 'The small text above the clients section title',
  },
  {
    content_key: 'home.clients.title',
    content_value: 'Trusted By Leading Organizations',
    content_type: 'text',
    group_name: 'homepage',
    label: 'Clients Section Title',
    description: 'The main title for the clients section',
  },
  {
    content_key: 'home.clients.description',
    content_value: 'Highlight that HB Furniture has successfully delivered workspace solutions for respected organizations across multiple industries.',
    content_type: 'text',
    group_name: 'homepage',
    label: 'Clients Section Description',
    description: 'The description text for the clients section',
  },

  // Homepage CTA Section
  {
    content_key: 'home.cta.subtitle',
    content_value: 'Let\'s Create Something Great Together',
    content_type: 'text',
    group_name: 'homepage',
    label: 'CTA Section Subtitle',
    description: 'The small text above the CTA section title',
  },
  {
    content_key: 'home.cta.title',
    content_value: 'Ready To Transform Your Workspace?',
    content_type: 'text',
    group_name: 'homepage',
    label: 'CTA Section Title',
    description: 'The main title for the CTA section',
  },
  {
    content_key: 'home.cta.description',
    content_value: 'From executive offices to complete workplace solutions, HB Furniture helps organizations create productive environments that inspire performance.',
    content_type: 'text',
    group_name: 'homepage',
    label: 'CTA Section Description',
    description: 'The description text for the CTA section',
  },
  {
    content_key: 'home.cta.cta_text',
    content_value: 'Request Consultation',
    content_type: 'text',
    group_name: 'homepage',
    label: 'CTA Button Text',
    description: 'The text for the CTA button',
  },
  {
    content_key: 'home.cta.cta_link',
    content_value: '/contact',
    content_type: 'text',
    group_name: 'homepage',
    label: 'CTA Button Link',
    description: 'The URL for the CTA button',
  },
  {
    content_key: 'home.cta.background_image',
    content_value: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=2000&q=80',
    content_type: 'image',
    group_name: 'homepage',
    label: 'CTA Background Image',
    description: 'The background image for the CTA section',
  },

  // Footer
  {
    content_key: 'footer.description',
    content_value: 'Crafting inspired workspaces with innovative furniture solutions designed for comfort, style and productivity.',
    content_type: 'text',
    group_name: 'footer',
    label: 'Footer Description',
    description: 'The description text in the footer',
  },
  {
    content_key: 'footer.address',
    content_value: 'Plot 56 Service Rd N, I-10/3,\nIslamabad, 44000, Pakistan',
    content_type: 'text',
    group_name: 'footer',
    label: 'Footer Address',
    description: 'The physical address in the footer',
  },
  {
    content_key: 'footer.phones',
    content_value: '["+971 524331920", "0321 5112403", "0319 2004722"]',
    content_type: 'array',
    group_name: 'footer',
    label: 'Footer Phone Numbers',
    description: 'JSON array of phone numbers',
  },
  {
    content_key: 'footer.email',
    content_value: 'hbfurniture64@gmail.com',
    content_type: 'text',
    group_name: 'footer',
    label: 'Footer Email',
    description: 'The email address in the footer',
  },

  // About Page
  {
    content_key: 'about.hero.title',
    content_value: 'A Legacy of Craftsmanship.\nA Future of Workspaces.',
    content_type: 'text',
    group_name: 'about',
    label: 'About Page Hero Title',
    description: 'The hero title for the about page',
  },
  {
    content_key: 'about.hero.subtitle',
    content_value: 'From a small 1964 workshop to Pakistan\'s leading workspace execution partner.',
    content_type: 'text',
    group_name: 'about',
    label: 'About Page Hero Subtitle',
    description: 'The hero subtitle for the about page',
  },
  {
    content_key: 'about.hero.background_image',
    content_value: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=2000',
    content_type: 'image',
    group_name: 'about',
    label: 'About Page Hero Background',
    description: 'The background image for the about page hero',
  },
  {
    content_key: 'about.foundation.title',
    content_value: 'The Foundation of Excellence',
    content_type: 'text',
    group_name: 'about',
    label: 'Foundation Section Title',
    description: 'The title for the foundation section on about page',
  },
  {
    content_key: 'about.foundation.paragraph1',
    content_value: 'Founded in 1964 by Mr. Tahir Hassan Gardezi at the ambitious age of 23, HB Furniture began with a singular vision: to bring uncompromising European craftsmanship to Pakistan. Trained extensively in Sweden, Mr. Gardezi instilled a culture of precision and structural integrity that remains the bedrock of our operations today.',
    content_type: 'text',
    group_name: 'about',
    label: 'Foundation Paragraph 1',
    description: 'First paragraph of foundation section',
  },
  {
    content_key: 'about.foundation.paragraph2',
    content_value: 'Over the decades, we have evolved from a bespoke workshop into a formidable turnkey execution partner. Now under second-generation leadership, we blend heritage woodworking techniques with state-of-the-art architectural technology to deliver workspaces that define corporate legacy.',
    content_type: 'text',
    group_name: 'about',
    label: 'Foundation Paragraph 2',
    description: 'Second paragraph of foundation section',
  },
  {
    content_key: 'about.foundation.image',
    content_value: '/90.png',
    content_type: 'image',
    group_name: 'about',
    label: 'Foundation Section Image',
    description: 'The image for the foundation section',
  },
]
